### PR TITLE
Kyleangelich1/dev 81 art to heart program page

### PR DESCRIPTION
**Pull request by KyleA99**
I think it's done?

### CODE REVIEW

**Comment by GeorgeIpsum** [comment]
image

not a fan of hwo the background contrasts here. Let's work with the art departments to separate this heart crayon graphic and the ted crayon sketches into their own layers and move them to the foreground so we can use the card as a proper background

**Comment by GeorgeIpsum** [comment]
image
why he :O

**Comment by GeorgeIpsum** [comment]
image

layout works fine here on mobile but lets do something dual column on wider screens.

**Comment by GeorgeIpsum** [comment]
image

separating this form and the application form feels like REALLY poopy UX, and will at some point confuse someone. let's either remove this altogether or figure out a way to incorporate the form here (does google forms allow for embeds?)

**Review by GeorgeIpsum — CHANGES_REQUESTED** [review]
Very epic. thank you

**Review by zshawdev — APPROVED** [review]
Great work Kyle!

**Pull request merged**
